INSERT INTO public.products (name, category, price, unit, stock, image, description) VALUES
('Red Apples', 'Fruits', 120, 'kg', 150, '/images/products/apples.jpg', 'Fresh, crisp red apples sourced directly from farms. Rich in fiber and vitamin C.'),
('Bananas', 'Fruits', 50, 'dozen', 200, '/images/products/bananas.png', 'Bright yellow bananas, perfectly ripe. High in potassium and natural sugars.'),
('Mangoes', 'Fruits', 150, 'kg', 100, '/images/products/mangoes.jpg', 'Golden mangoes, the king of fruits. Seasonal specialty with sweet, juicy flesh.'),
('Oranges', 'Fruits', 80, 'kg', 120, '/images/products/oranges.jpg', 'Juicy, sweet oranges packed with vitamin C. Great for fresh juice or eating whole.'),
('Strawberries', 'Fruits', 180, 'box', 60, '/images/products/strawberries.jpg', 'Fresh, red strawberries with natural sweetness. Rich in vitamin C and antioxidants.'),
('Green Grapes', 'Fruits', 150, 'kg', 80, '/images/products/green-grapes.png', 'Crisp, seedless green grapes. Sweet and refreshing. Perfect for snacking or desserts.'),
('Watermelon', 'Fruits', 40, 'piece', 110, '/images/products/watermelon.png', 'Large, sweet watermelons. 92% water content, perfect for hydration in summer.'),
('Papaya', 'Fruits', 60, 'piece', 90, '/images/products/papaya.jpg', 'Golden, sweet papayas. Aids digestion with natural enzymes. Rich in vitamin A and C.'),
('Pineapple', 'Fruits', 70, 'piece', 75, '/images/products/pineapple.jpg', 'Fresh, juicy pineapples with natural sweetness. High in vitamin C and bromelain.'),
('Pomegranate', 'Fruits', 180, 'piece', 50, '/images/products/pomegranate.png', 'Ruby red pomegranates, full of antioxidants. Packed with arils. Premium quality fruit.'),
('Tomato', 'Vegetables', 48, 'kg', 220, '/images/products/tomatoes.jpg', 'Fresh red tomatoes, juicy and flavorful. Essential for Indian cooking. Rich in lycopene.'),
('Potato', 'Vegetables', 25, 'kg', 300, 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=400&fit=crop', 'Starchy potatoes, versatile staple vegetable. Perfect for cooking, frying, boiling.'),
('Onion', 'Vegetables', 70, 'kg', 250, 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=400&fit=crop', 'Fresh red onions with strong flavor. Essential for Indian cooking. Long storage life.'),
('Spinach', 'Vegetables', 35, 'bunch', 140, 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop', 'Fresh green spinach, nutrient-dense leafy green. Rich in iron and calcium.'),
('Carrot', 'Vegetables', 45, 'kg', 180, 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop', 'Bright orange carrots, sweet and crunchy. High in beta-carotene. Great for eyes and skin.'),
('Capsicum', 'Vegetables', 45, 'kg', 140, '/images/products/capsicum.jpg', 'Colorful bell peppers (green). Sweet and crunchy. Great for salads and cooking.'),
('Cauliflower', 'Vegetables', 40, 'piece', 90, '/images/products/cauliflower.jpg', 'Fresh cauliflower head, white and dense. Low carb, keto-friendly. Great roasted or curried.'),
('Broccoli', 'Vegetables', 55, 'piece', 70, '/images/products/broccoli.png', 'Fresh, green broccoli crowns. Nutrient-dense superfood. Great for immunity and health.'),
('Cucumber', 'Vegetables', 35, 'kg', 130, 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=400&h=400&fit=crop', 'Cool, refreshing cucumbers. Mostly water, hydrating vegetable. Perfect for salads and pickles.'),
('Green Chilli', 'Vegetables', 83, 'kg', 85, '/images/products/green-chilli.jpg', 'Spicy green chillies, sharp heat. Essential for Indian cooking. High in vitamin C.');