-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text unique not null,
  category text not null,
  price numeric not null,
  original_price numeric,
  unit text not null,
  stock integer not null default 0,
  image text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access on products"
  on public.products
  for select
  to public
  using (true);

-- Create policy to allow authenticated users to insert/update (for the seeding script if authenticated, or you can temporarily use service_role)
-- For simplicity of seeding using the service role or anon key, we'll allow all operations temporarily if needed, 
-- but it's safer to use the service role key. If using anon key for seeding, uncomment the below:
create policy "Allow public insert/update temporarily"
  on public.products
  for all
  to public
  using (true)
  with check (true);
